# Generated by Django 5.0.5 on 2024-05-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_category_event_banner_image_event_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.RemoveField(
            model_name='event',
            name='banner_image',
        ),
        migrations.AddField(
            model_name='event',
            name='banner_image_url',
            field=models.URLField(default='https://images.google.com/'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
