# Generated by Django 5.0.5 on 2024-05-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_category_remove_event_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
